package com.mrenann.mercadolivre.detailsScreen.presentation.screenModel

class DetailsScreenModelTest

//class DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTestclass DetailsScreenModelTest