name: Run detekt

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Set up reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893
        with:
          reviewdog_version: latest

      - name: Run detekt with reviewdog
        run: |
          mkdir -p $GITHUB_WORKSPACE/reports
          
          ./gradlew detekt --quiet --no-daemon || gradlew_exit_code=$?
          
          if [ -f "$GITHUB_WORKSPACE/reports/detekt.xml" ]; then
            reviewdog \
              -f=checkstyle \
              -name="detekt" \
              -reporter=github-pr-review \
              -filter-mode=nofilter \
              -fail-on-error=false \
              < $GITHUB_WORKSPACE/reports/detekt.xml
          else
            echo "⚠️ Relatório não encontrado em: $GITHUB_WORKSPACE/reports/detekt.xml"
            find $GITHUB_WORKSPACE -name "detekt.xml" || echo "Nenhum relatório encontrado"
          fi
          
          if [ -n "${gradlew_exit_code:-}" ]; then
            echo "❌ Detekt encontrou problemas (código: $gradlew_exit_code)"
            exit $gradlew_exit_code
          else
            echo "✅ Detekt passou sem erros!"
            echo "## ✅ Analise do Detekt passou corretamente" >> $GITHUB_STEP_SUMMARY
          
            echo "### Nenhum problema encontrado" >> $GITHUB_STEP_SUMMARY
            echo "O código está seguindo todas as regras do Detekt corretamente!" >> $GITHUB_STEP_SUMMARY
          fi
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}